language: generic
sudo: required
services:
  - docker

# before_install:
#   - docker build -t gudunku/react-client-test -f ./client/Dockerfile.dev ./client

# script:
#   - docker run -e CI=true gudunku/react-client-test npm run test

after_success:
  - docker build -t gudunku/complex-app-client ./client
  - docker build -t gudunku/complex-app-server ./server
  - docker build -t gudunku/complex-app-worker ./worker
  # Login to docker CLI
  - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
  # Take those images and push them to docker hub
  - docker push gudunku/complex-app-client
  - docker push gudunku/complex-app-server
  - docker push gudunku/complex-app-worker
